[package]
name = "storing_and_retrieving_data"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "toml"
path = "src/toml.rs"

[[bin]]
name = "sqlite"
path = "src/sqlite.rs"

[dependencies]
rusqlite = "0.23.0"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
